Proper error handling at edit action

diff --git a/lib/keyringer/actions/edit b/lib/keyringer/actions/edit
--- a/lib/keyringer/actions/edit
+++ b/lib/keyringer/actions/edit
@@ -44,5 +44,18 @@ $APP "$TMPWORK"
 # Encrypt again
 $GPG --yes -o "$KEYDIR/$FILE" --use-agent --armor -e -s $(keyringer_recipients "$RECIPIENTS_FILE") "$TMPWORK"
 
+# Check exit status
+errcrypt="$?"
+
 # Remove temp file
 keyringer_unset_tmpfile "$TMPWORK"
+
+# Check exit status again
+errwipe="$?"
+
+# Error handling must be done after temp file removal
+if [ "$errcrypt" != "0" ]; then
+  exit "$errcrypt"
+elif [ "$errwipe" != "0" ]; then
+  exit $errwipe
+fi
